# Generated by Django 4.2.11 on 2026-02-26 16:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_remove_customerprofile_delivery_address_and_more"),
        ("orders", "0001_initial"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="producerorder",
            unique_together={("customer_order", "producer")},
        ),
    ]
