# Generated by Django 4.2.11 on 2026-05-04 00:04

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_backfill_customer_profiles'),
        ('marketplace', '0004_surplus_deal'),
        ('orders', '0002_alter_producerorder_unique_together'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecurringOrderTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('rrule', models.TextField(help_text='iCal RRULE string defining the recurrence schedule')),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recurring_templates', to='accounts.customerprofile')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RecurringOrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recurring_order_items', to='marketplace.product')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.recurringordertemplate')),
            ],
        ),
        migrations.CreateModel(
            name='RecurringOrderInstance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('scheduled_for', models.DateField()),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('placed', 'Placed'), ('skipped', 'Skipped')], default='scheduled', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recurring_instance', to='orders.customerorder')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instances', to='orders.recurringordertemplate')),
            ],
            options={
                'ordering': ['scheduled_for'],
            },
        ),
        migrations.AddConstraint(
            model_name='recurringorderitem',
            constraint=models.UniqueConstraint(fields=('template', 'product'), name='recurring_order_item_pk'),
        ),
        migrations.AddConstraint(
            model_name='recurringorderinstance',
            constraint=models.UniqueConstraint(fields=('template', 'scheduled_for'), name='recurring_instance_unique_per_date'),
        ),
    ]
