# Generated by Django 4.2.11 on 2026-05-06 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_recurringordertemplate_recurringorderitem_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recurringorderinstance',
            name='quantity_overrides',
            field=models.JSONField(blank=True, default=dict, help_text='Override quantities for this specific instance. Format: {product_id: quantity}'),
        ),
    ]
