# Generated by Django 4.2.11 on 2026-05-06 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_backfill_customer_profiles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='communitygroupprofile',
            name='organisation_type',
            field=models.CharField(choices=[('food_bank', 'Food Bank'), ('school', 'School/Educational'), ('community_center', 'Community Center'), ('charity', 'Charity/Non-profit'), ('restaurant', 'Restaurant/Catering'), ('other', 'Other')], default='other', help_text='Type of organisation', max_length=100),
        ),
    ]
