services:
  db:
    image: ghcr.io/mohamed-elkiky/ufcftr-30-3---distributed-and-enterprise-software-development/db:latest
    build:
      context: ./docker/postgres
    environment:
      POSTGRES_DB: mydb
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U myuser -d mydb" ]
      interval: 5s
      timeout: 5s
      retries: 10

  web:
    image: ghcr.io/mohamed-elkiky/ufcftr-30-3---distributed-and-enterprise-software-development/web:latest
    build: .
    command: gunicorn brfn.wsgi:application --bind 0.0.0.0:8000 --workers 3
    volumes:
      - .:/app
      - static_volume:/app/staticfiles
      - media_volume:/app/media
    expose:
      - "8000"
    depends_on:
      db:
        condition: service_healthy
    environment:
      - PYTHONUNBUFFERED=1
      - DJANGO_SETTINGS_MODULE=brfn.settings.docker
      - DJANGO_DB_NAME=mydb
      - DJANGO_DB_USER=myuser
      - DJANGO_DB_PASSWORD=mypassword
      - DJANGO_DB_HOST=db
      - DJANGO_DB_PORT=5432
      - DATABASE_URL=postgresql://myuser:mypassword@db:5432/mydb
      - AI_API_BASE_URL=http://host.docker.internal:5000
  nginx:
    image: nginx:1.25-alpine
    ports:
      - "80:80"
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - static_volume:/app/staticfiles
      - media_volume:/app/media
    depends_on:
      - web

volumes:
  postgres_data:
  static_volume:
  media_volume: