# Generated by Django 4.2.11 on 2026-02-25 17:09

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Allergen",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.TextField(blank=True, null=True, unique=True)),
            ],
            options={
                "db_table": "allergen",
            },
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True, default="")),
                ("price_pence", models.PositiveIntegerField()),
                ("unit", models.CharField(max_length=50)),
                (
                    "availability",
                    models.CharField(
                        choices=[
                            ("in_season", "in_season"),
                            ("available_year_round", "available_year_round"),
                            ("out_of_season", "out_of_season"),
                            ("unavailable", "unavailable"),
                        ],
                        default="available_year_round",
                        max_length=32,
                    ),
                ),
                (
                    "seasonal_start_month",
                    models.SmallIntegerField(blank=True, null=True),
                ),
                ("seasonal_end_month", models.SmallIntegerField(blank=True, null=True)),
                ("stock_qty", models.PositiveIntegerField(default=0)),
                ("low_stock_threshold", models.PositiveIntegerField(default=10)),
                ("organic_certified", models.BooleanField(default=False)),
                ("harvest_date", models.DateField(blank=True, null=True)),
                ("best_before_date", models.DateField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "product",
            },
        ),
        migrations.CreateModel(
            name="ProductCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.TextField(unique=True)),
                ("created_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "product_category",
            },
        ),
        migrations.CreateModel(
            name="ProductImage",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("url", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(blank=True, null=True)),
                (
                    "product",
                    models.ForeignKey(
                        db_column="product_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="marketplace.product",
                    ),
                ),
            ],
            options={
                "db_table": "product_image",
            },
        ),
        migrations.CreateModel(
            name="ProductAllergen",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "allergen",
                    models.ForeignKey(
                        db_column="allergen_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="product_links",
                        to="marketplace.allergen",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        db_column="product_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="allergen_links",
                        to="marketplace.product",
                    ),
                ),
            ],
            options={
                "db_table": "product_allergen",
            },
        ),
        migrations.AddField(
            model_name="product",
            name="category",
            field=models.ForeignKey(
                blank=True,
                db_column="category_id",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="products",
                to="marketplace.productcategory",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="producer",
            field=models.ForeignKey(
                blank=True,
                db_column="producer_id",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="products",
                to="accounts.producerprofile",
            ),
        ),
        migrations.AddConstraint(
            model_name="productallergen",
            constraint=models.UniqueConstraint(
                fields=("product", "allergen"), name="product_allergen_pk"
            ),
        ),
    ]
