# Generated by Django 4.2.11 on 2026-03-17 13:32

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0003_productimage_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='SurplusDeal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('discount_bp', models.PositiveIntegerField(help_text='Discount in basis points (e.g. 2000 = 20%)')),
                ('expires_at', models.DateTimeField()),
                ('note', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.OneToOneField(db_column='product_id', on_delete=django.db.models.deletion.CASCADE, related_name='surplus_deal', to='marketplace.product')),
            ],
            options={
                'db_table': 'surplus_deal',
            },
        ),
    ]
