# Generated by Django 4.2.11 on 2026-05-04 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contentpost',
            old_name='season',
            new_name='seasonal_tag',
        ),
        migrations.RemoveField(
            model_name='contentpost',
            name='content',
        ),
        migrations.RemoveField(
            model_name='contentpost',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='contentpost',
            name='description',
        ),
        migrations.RemoveField(
            model_name='contentpost',
            name='ingredients',
        ),
        migrations.AddField(
            model_name='contentpost',
            name='body',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contentpost',
            name='kind',
            field=models.CharField(choices=[('recipe', 'Recipe'), ('farm_story', 'Farm Story'), ('storage_guide', 'Storage Guide')], default='recipe', max_length=20),
        ),
    ]
