# Generated by Django 4.2.11 on 2026-02-25 17:09

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("orders", "0001_initial"),
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProducerSettlement",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("week_start", models.DateField()),
                ("week_end", models.DateField()),
                ("total_order_value_pence", models.IntegerField(default=0)),
                ("commission_pence", models.IntegerField(default=0)),
                ("settlement_amount_pence", models.IntegerField(default=0)),
                ("order_count", models.IntegerField(default=0)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("processed", "Processed"),
                            ("paid", "Paid"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "payment_reference",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("paid_at", models.DateTimeField(blank=True, null=True)),
                (
                    "producer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="settlements",
                        to="accounts.producerprofile",
                    ),
                ),
            ],
            options={
                "ordering": ["-week_start"],
                "unique_together": {("producer", "week_start")},
            },
        ),
        migrations.CreateModel(
            name="PaymentTransaction",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("amount_pence", models.IntegerField()),
                (
                    "payment_method",
                    models.CharField(
                        choices=[
                            ("card", "Card"),
                            ("bank_transfer", "Bank Transfer"),
                            ("mock", "Mock Payment (Testing)"),
                        ],
                        default="mock",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                            ("refunded", "Refunded"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "external_reference",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "order",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payment",
                        to="orders.customerorder",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CommissionRecord",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("order_value_pence", models.IntegerField()),
                (
                    "commission_rate",
                    models.DecimalField(decimal_places=4, default=0.05, max_digits=5),
                ),
                ("commission_pence", models.IntegerField()),
                ("producer_payout_pence", models.IntegerField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "producer_order",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="commission_record",
                        to="orders.producerorder",
                    ),
                ),
                (
                    "settlement",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="commission_records",
                        to="payments.producersettlement",
                    ),
                ),
            ],
        ),
    ]
